//! Turn the branding's design tokens into Rust.
//!
//! `assets/branding/tokens.json` is the hand-off from the design canvas and the
//! one place a colour, a radius or a type size is decided (issue #207). This
//! reads it and writes `tokens.rs` into `OUT_DIR`, which `theme.rs` includes.
//!
//! Generated at build time rather than committed on purpose. The wire codegen
//! in this repository commits its output because it crosses into Kotlin and
//! TypeScript, where a build script cannot reach, and pays for that with a
//! drift test. Nothing here leaves Rust, so there is no artifact to go stale
//! and nothing to check: change the token file and the constants change with
//! it, or the build fails.
//!
//! Two kinds of output, because there are two kinds of consumer:
//!
//! * typed constants, for the code that measures and draws;
//! * a substitution table, for the stylesheet, which is a string and wants
//!   text.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let repo_root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../..")
        .canonicalize()
        .expect("the crate sits two levels below the repository root");
    let tokens_path = repo_root.join("assets/branding/tokens.json");

    println!("cargo:rerun-if-changed={}", tokens_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = std::fs::read_to_string(&tokens_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", tokens_path.display()));
    let tokens: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("{} is not JSON: {e}", tokens_path.display()));

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from assets/branding/tokens.json — do not edit.\n\
         /// The branding's design tokens, as Rust.\n\
         #[allow(dead_code)]\n\
         pub mod tokens {\n",
    );

    // Every token that is a plain `$value`, flattened to `group-name`. The
    // stylesheet wants all of them as text; only some become typed constants.
    let mut css: BTreeMap<String, String> = BTreeMap::new();

    for group in [
        "color", "font", "stroke", "radius", "space", "shadow", "motion", "opacity",
    ] {
        let Some(table) = tokens.get(group).and_then(|g| g.as_object()) else {
            panic!("tokens.json has no `{group}` table");
        };
        for (name, body) in table {
            let Some(value) = body.get("$value") else {
                continue;
            };
            let text = match value {
                serde_json::Value::String(s) => s.clone(),
                serde_json::Value::Number(n) => n.to_string(),
                other => panic!("{group}.{name} is neither string nor number: {other}"),
            };
            css.insert(format!("{group}-{name}"), text);
        }
    }

    // `type` is the one table whose entries are objects rather than `$value`s:
    // a size, a weight and sometimes a line height.
    let type_table = tokens
        .get("type")
        .and_then(|t| t.as_object())
        .expect("tokens.json has no `type` table");
    for (name, body) in type_table {
        for field in ["size", "weight"] {
            if let Some(n) = body.get(field).and_then(|v| v.as_f64()) {
                css.insert(format!("type-{name}-{field}"), trim_float(n));
            }
        }
    }

    // The field's sheen is a gradient, so its end stop — the enamel at the very
    // edge of the screen — is not a token of its own. The edge fade has to
    // match it exactly or it shows as a seam (see `theme.rs`), so pull it out
    // rather than write it down twice.
    let sheen = css
        .get("color-enamel-sheen")
        .expect("tokens.json has no color.enamel-sheen");
    let edge = first_hex(sheen)
        .unwrap_or_else(|| panic!("no #rrggbb stop found in color.enamel-sheen: {sheen}"));
    let (r, g, b) = hex_to_u8(&edge);
    css.insert("color-enamel-edge".into(), edge.clone());
    css.insert("color-enamel-edge-rgb".into(), format!("{r}, {g}, {b}"));

    // ---- typed constants -------------------------------------------------
    for (name, key) in [
        ("INK", "color-ink"),
        ("YELLOW", "color-yellow"),
        ("CREAM", "color-cream"),
    ] {
        let hex = &css[key];
        let (r, g, b) = hex_to_u8(hex);
        writeln!(out, "    /// `{key}` from tokens.json.").unwrap();
        writeln!(out, "    pub const {name}: &str = \"{hex}\";").unwrap();
        // Emitted already divided. Writing `255.0 / 255.0` would be clearer
        // about where the number came from, but clippy's `eq_op` rejects it,
        // and generated code has to pass the same lints as written code.
        writeln!(
            out,
            "    /// `{key}`, as the components cairo draws with.\n    \
             pub const {name}_RGB: (f64, f64, f64) = ({:?}, {:?}, {:?});",
            f64::from(r) / 255.0,
            f64::from(g) / 255.0,
            f64::from(b) / 255.0,
        )
        .unwrap();
    }

    for (name, key) in [
        ("ITEM_W", "space-item-w"),
        ("ITEM_ROW_H", "space-item-row-h"),
        ("ICON_PX", "space-icon"),
        ("HUD_H", "space-hud-h"),
        ("ROWS_PER_STACK", "space-rows"),
        ("ITEM_FONT_PX", "type-item-size"),
    ] {
        let v = css[key]
            .parse::<f64>()
            .unwrap_or_else(|_| panic!("{key} is not a number"));
        writeln!(out, "    /// `{key}` from tokens.json.").unwrap();
        writeln!(out, "    pub const {name}: i32 = {};", v as i64).unwrap();
    }

    let keyline: f64 = css["stroke-keyline"].parse().unwrap();
    writeln!(out, "    /// `stroke-keyline` from tokens.json.").unwrap();
    writeln!(out, "    pub const KEYLINE: f64 = {keyline:?};").unwrap();

    // ---- the stylesheet's substitution table -----------------------------
    writeln!(
        out,
        "\n    /// Every token as text, keyed the way `@name@` placeholders in\n    \
         /// the stylesheet spell it.\n    \
         pub const CSS: &[(&str, &str)] = &["
    )
    .unwrap();
    for (name, value) in &css {
        writeln!(out, "        (\"{name}\", {value:?}),").unwrap();
    }
    out.push_str("    ];\n}\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("tokens.rs");
    std::fs::write(&dest, out).expect("cannot write the generated tokens");
}

/// `4.0` prints as `4`, so a size written as an integer stays one in the CSS.
fn trim_float(n: f64) -> String {
    if n.fract() == 0.0 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

fn first_hex(s: &str) -> Option<String> {
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'#' && i + 7 <= bytes.len() {
            let candidate = &s[i..i + 7];
            if candidate[1..].bytes().all(|c| c.is_ascii_hexdigit()) {
                return Some(candidate.to_string());
            }
        }
        i += 1;
    }
    None
}

fn hex_to_u8(hex: &str) -> (u8, u8, u8) {
    let h = hex.trim_start_matches('#');
    let part = |i: usize| u8::from_str_radix(&h[i..i + 2], 16).expect("a #rrggbb colour");
    (part(0), part(2), part(4))
}
