//! Turn the branding's design tokens into Rust.
//!
//! `assets/branding/tokens.json` is the hand-off from the design canvas and the
//! one place a colour, a radius or a type size is decided (issue #207). This
//! reads it and writes `tokens.rs` into `OUT_DIR`, which `lib.rs` includes.
//!
//! Generated at build time rather than committed on purpose. The wire codegen
//! in this repository commits its output because it crosses into Kotlin and
//! TypeScript, where a build script cannot reach, and pays for that with a
//! drift test. Nothing here leaves Rust, so there is no artifact to go stale
//! and nothing to check: change the token file and the constants change with
//! it, or the build fails.
//!
//! Two kinds of output, because there are two kinds of consumer:
//!
//! * typed constants, for the code that measures and draws;
//! * a substitution table, for the stylesheets, which are strings and want
//!   text.
//!
//! **Every token gets both**, named after its own key rather than after the
//! consumer that wanted it: `space.hud-h` is `SPACE_HUD_H`, `color.ink` is
//! `COLOR_INK` and `COLOR_INK_RGB`. The list used to be hand-maintained here,
//! which meant a second crate wanting a token had to come back and add it; the
//! naming is mechanical so that it does not.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let repo_root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../..")
        .canonicalize()
        .expect("the crate sits two levels below the repository root");
    let tokens_path = repo_root.join("assets/branding/tokens.json");

    println!("cargo:rerun-if-changed={}", tokens_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = std::fs::read_to_string(&tokens_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", tokens_path.display()));
    let tokens: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("{} is not JSON: {e}", tokens_path.display()));

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from assets/branding/tokens.json — do not edit.\n\
         /// The branding's design tokens, as Rust.\n\
         #[allow(dead_code)]\n\
         pub mod tokens {\n",
    );

    // Every token that is a plain `$value`, flattened to `group-name`. The
    // stylesheets want all of them as text; the typed pass below takes the ones
    // that are a number or a colour.
    let mut css: BTreeMap<String, String> = BTreeMap::new();

    for group in [
        "color", "font", "stroke", "radius", "space", "shadow", "motion", "opacity",
    ] {
        let Some(table) = tokens.get(group).and_then(|g| g.as_object()) else {
            panic!("tokens.json has no `{group}` table");
        };
        for (name, body) in table {
            let Some(value) = body.get("$value") else {
                continue;
            };
            let text = match value {
                serde_json::Value::String(s) => s.clone(),
                serde_json::Value::Number(n) => n.to_string(),
                other => panic!("{group}.{name} is neither string nor number: {other}"),
            };
            css.insert(format!("{group}-{name}"), text);
        }
    }

    // `type` is the one table whose entries are objects rather than `$value`s:
    // a size, a weight and sometimes a line height.
    let type_table = tokens
        .get("type")
        .and_then(|t| t.as_object())
        .expect("tokens.json has no `type` table");
    for (name, body) in type_table {
        for field in ["size", "weight", "lineHeight"] {
            if let Some(n) = body.get(field).and_then(|v| v.as_f64()) {
                // `lineHeight` in the design file, `line-height` everywhere a
                // stylesheet or a key is written.
                css.insert(format!("type-{name}-{}", kebab(field)), trim_float(n));
            }
        }
    }

    // Every colour also as bare rgba components, because a stylesheet that
    // wants a *translucent* wash of one — a hover state, a tint — cannot get
    // there from `#rrggbb`: CSS has no syntax for "this colour at 14%". Keyed
    // `<name>-rgb`, which is not a token name the design file can collide with
    // and so never becomes a constant of its own.
    for (key, value) in css.clone() {
        if is_hex(&value) {
            let (r, g, b) = hex_to_u8(&value);
            css.insert(format!("{key}-rgb"), format!("{r}, {g}, {b}"));
        }
    }

    // The field's sheen is a gradient, so its end stop — the enamel at the very
    // edge of the screen — is not a token of its own. The edge fade has to
    // match it exactly or it shows as a seam (see the launcher's `theme.rs`), so
    // pull it out rather than write it down twice.
    let sheen = css
        .get("color-enamel-sheen")
        .expect("tokens.json has no color.enamel-sheen");
    let edge = first_hex(sheen)
        .unwrap_or_else(|| panic!("no #rrggbb stop found in color.enamel-sheen: {sheen}"));
    let (r, g, b) = hex_to_u8(&edge);
    css.insert("color-enamel-edge".into(), edge.clone());
    css.insert("color-enamel-edge-rgb".into(), format!("{r}, {g}, {b}"));

    // ---- typed constants -------------------------------------------------
    //
    // A token that parses as a number becomes an `i32` when it is whole and an
    // `f64` when it is not, because that is what the code measuring with it
    // wants and a cast at every use site reads worse than the one place the
    // type is decided. A token that is a plain `#rrggbb` becomes both the hex
    // string and the triple cairo and GSK draw with. Everything else — the
    // gradients, the font stacks, the shadow recipes, `120ms` — is text only,
    // and reaches the stylesheet through `CSS`.
    for (key, value) in &css {
        let name = screaming(key);
        if let Ok(n) = value.parse::<f64>() {
            writeln!(out, "    /// `{key}` from tokens.json.").unwrap();
            if n.fract() == 0.0 {
                writeln!(out, "    pub const {name}: i32 = {};", n as i64).unwrap();
            } else {
                writeln!(out, "    pub const {name}: f64 = {n:?};").unwrap();
            }
        } else if is_hex(value) {
            let (r, g, b) = hex_to_u8(value);
            writeln!(out, "    /// `{key}` from tokens.json.").unwrap();
            writeln!(out, "    pub const {name}: &str = \"{value}\";").unwrap();
            // Emitted already divided. Writing `255.0 / 255.0` would be clearer
            // about where the number came from, but clippy's `eq_op` rejects it,
            // and generated code has to pass the same lints as written code.
            writeln!(
                out,
                "    /// `{key}`, as the components cairo and GSK draw with.\n    \
                 pub const {name}_RGB: (f64, f64, f64) = ({:?}, {:?}, {:?});",
                f64::from(r) / 255.0,
                f64::from(g) / 255.0,
                f64::from(b) / 255.0,
            )
            .unwrap();
        }
    }

    // ---- the stylesheets' substitution table -----------------------------
    writeln!(
        out,
        "\n    /// Every token as text, keyed the way `@name@` placeholders in\n    \
         /// a stylesheet spell it.\n    \
         pub const CSS: &[(&str, &str)] = &["
    )
    .unwrap();
    for (name, value) in &css {
        writeln!(out, "        (\"{name}\", {value:?}),").unwrap();
    }
    out.push_str("    ];\n}\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("tokens.rs");
    std::fs::write(&dest, out).expect("cannot write the generated tokens");
}

/// `lineHeight` -> `line-height`: the design file writes its field names the
/// way JSON usually does, and everything downstream writes them the way CSS
/// does.
fn kebab(field: &str) -> String {
    let mut out = String::with_capacity(field.len() + 2);
    for c in field.chars() {
        if c.is_ascii_uppercase() {
            out.push('-');
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// `color-muted-on-dark` -> `COLOR_MUTED_ON_DARK`: the token's own key, as a
/// Rust constant.
fn screaming(key: &str) -> String {
    key.replace('-', "_").to_ascii_uppercase()
}

/// `4.0` prints as `4`, so a size written as an integer stays one in the CSS.
fn trim_float(n: f64) -> String {
    if n.fract() == 0.0 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

fn is_hex(s: &str) -> bool {
    s.len() == 7 && s.starts_with('#') && s[1..].bytes().all(|c| c.is_ascii_hexdigit())
}

fn first_hex(s: &str) -> Option<String> {
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'#' && i + 7 <= bytes.len() {
            let candidate = &s[i..i + 7];
            if is_hex(candidate) {
                return Some(candidate.to_string());
            }
        }
        i += 1;
    }
    None
}

fn hex_to_u8(hex: &str) -> (u8, u8, u8) {
    let h = hex.trim_start_matches('#');
    let part = |i: usize| u8::from_str_radix(&h[i..i + 2], 16).expect("a #rrggbb colour");
    (part(0), part(2), part(4))
}
