//! IPC wire types.
//!
//! Requests carry a JSON-RPC-style `{ method, params }` pair that the
//! server dispatches through `lunchbox_management::dispatch_json`
//! (generated by the `#[management_rpc]` attribute on
//! `ManagementService`). The previous `Command` tagged enum lived
//! here for years but had to be updated in three places for every
//! new operation — the trait, the enum, and the server's giant
//! match. Method-name dispatch collapses that to just the trait.
//!
//! Responses carry a `ResponseResult` which is either a plain
//! `serde_json::Value` (whatever the trait method returned, encoded
//! by `dispatch_json`) or an `ErrorInfo` with a typed code. Typed
//! clients use `lunchbox_ipc::IpcClient`'s helpers to skip the
//! `Value` step and get back the strongly-typed result.

use lunchbox_util::ClientId;
use serde::{Deserialize, Serialize};

use crate::{API_VERSION, ClientRole};

/// Request wrapper — every RPC over the lunchboxd IPC socket has this
/// shape.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    /// Correlates a request with its response on the same socket.
    pub request_id: u64,
    /// API version. Servers reject requests with the wrong version.
    pub api_version: u32,
    /// Method name, matching one of the wire names emitted by
    /// `dispatch_json` (see `docs/rpc-schema.json`).
    pub method: String,
    /// Method params, shape defined by the trait method's signature.
    /// `null`/absent is accepted for zero-arg methods.
    #[serde(default)]
    pub params: serde_json::Value,
}

impl Request {
    pub fn new(request_id: u64, method: impl Into<String>) -> Self {
        Self {
            request_id,
            api_version: API_VERSION,
            method: method.into(),
            params: serde_json::Value::Null,
        }
    }

    pub fn with_params(
        request_id: u64,
        method: impl Into<String>,
        params: serde_json::Value,
    ) -> Self {
        Self {
            request_id,
            api_version: API_VERSION,
            method: method.into(),
            params,
        }
    }
}

/// Response wrapper.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Response {
    pub request_id: u64,
    pub api_version: u32,
    pub result: ResponseResult,
}

impl Response {
    pub fn success(request_id: u64, value: serde_json::Value) -> Self {
        Self {
            request_id,
            api_version: API_VERSION,
            result: ResponseResult::Ok(value),
        }
    }

    pub fn error(request_id: u64, error: ErrorInfo) -> Self {
        Self {
            request_id,
            api_version: API_VERSION,
            result: ResponseResult::Err(error),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResponseResult {
    Ok(serde_json::Value),
    Err(ErrorInfo),
}

/// Error payload paired with a machine-readable code.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorInfo {
    pub code: ErrorCode,
    pub message: String,
}

impl ErrorInfo {
    pub fn new(code: ErrorCode, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }
}

/// Error codes covering both IPC-layer failures (rate limiting,
/// invalid version, permission denied by IPC role) and
/// `ManagementError` variants surfaced from the trait dispatch.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    // Framing / dispatch errors
    InvalidRequest,
    MethodNotFound,
    InvalidParams,
    // Business-layer errors from ManagementError
    NotFound,
    BadRequest,
    Forbidden,
    Conflict,
    Unprocessable,
    Internal,
    // IPC-layer concerns
    PermissionDenied,
    RateLimited,
}

/// Client connection info (set by IPC layer)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientInfo {
    pub client_id: ClientId,
    pub role: ClientRole,
    /// Unix UID if available
    pub uid: Option<u32>,
    /// Process name if available
    pub process_name: Option<String>,
}

impl ClientInfo {
    pub fn new(role: ClientRole) -> Self {
        Self {
            client_id: ClientId::new(),
            role,
            uid: None,
            process_name: None,
        }
    }

    pub fn with_uid(mut self, uid: u32) -> Self {
        self.uid = Some(uid);
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_round_trips_via_json() {
        let req = Request::with_params(1, "launch", serde_json::json!({"id": "steam-goo"}));
        let s = serde_json::to_string(&req).unwrap();
        let back: Request = serde_json::from_str(&s).unwrap();
        assert_eq!(back.request_id, 1);
        assert_eq!(back.method, "launch");
        assert_eq!(back.params["id"], "steam-goo");
    }

    #[test]
    fn response_ok_and_err_round_trip() {
        let ok = Response::success(1, serde_json::json!({"x": 1}));
        let s = serde_json::to_string(&ok).unwrap();
        let back: Response = serde_json::from_str(&s).unwrap();
        assert!(matches!(back.result, ResponseResult::Ok(_)));

        let err = Response::error(2, ErrorInfo::new(ErrorCode::NotFound, "no"));
        let s = serde_json::to_string(&err).unwrap();
        let back: Response = serde_json::from_str(&s).unwrap();
        match back.result {
            ResponseResult::Err(e) => {
                assert_eq!(e.code, ErrorCode::NotFound);
                assert_eq!(e.message, "no");
            }
            _ => panic!("expected err"),
        }
    }
}
