//! Render the config JSON Schema as TypeScript.
//!
//! The counterpart to [`crate::ts_types`], which does the same job for the
//! wire schema. Kept separate because the two schemas are written by different
//! generators: the wire types are hand-rolled JSON Schema tuned for the shapes
//! the daemon sends, while these come out of `schemars`, whose output uses
//! `$defs`/`$ref` throughout and carries Rust doc comments as `description`.
//!
//! Used for the config editor's mirrors of the `Raw*` types. The editor works
//! against a projection of `RawConfig` produced by the daemon's own parser, so
//! generating these from the same schema is what keeps the form fields and the
//! Rust struct from drifting apart the way the companion's hand-written Kotlin
//! mirrors twice did.
//!
//! Rust doc comments arrive as `description` and are re-emitted as JSDoc, which
//! is most of the reason the generated file is worth reading: the help text
//! beside a form field and the doc comment on the field agree by construction.

use serde_json::{Map, Value};

/// Render every definition in `schema`'s `$defs`, plus the root type.
pub fn render(schema: &Value, root_name: &str) -> String {
    let mut out = String::new();
    out.push_str(&header());

    let defs = schema
        .get("$defs")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();

    // Sorted so the output is stable across schemars versions and hash seeds.
    let mut names: Vec<&String> = defs.keys().collect();
    names.sort();

    for name in names {
        let def = &defs[name];
        out.push_str(&render_def(name, def));
        out.push('\n');
    }

    out.push_str(&render_def(root_name, schema));
    out
}

fn header() -> String {
    "\
// Generated by `cargo run -p shepherd-wire-codegen --bin rpc-codegen`.
// Do not edit by hand; a drift test fails CI when this file is stale.
//
// TypeScript mirrors of the `config.toml` schema in
// `crates/shepherd-config/src/schema.rs`.
//
// These describe the *projection* the editor renders — what serde produces
// when the daemon's parser reads a file — not TOML syntax. Where the file
// format accepts a shorthand (`input_compat = \"touch_to_mouse\"` as well as a
// list), the projection always carries the canonical form shown here.

"
    .to_string()
}

fn render_def(name: &str, def: &Value) -> String {
    let mut out = String::new();
    if let Some(doc) = doc_comment(def, 0) {
        out.push_str(&doc);
    }

    // A closed set of string constants: `oneOf` of `const` strings.
    if let Some(variants) = string_enum_variants(def) {
        out.push_str(&format!("export type {name} =\n"));
        for (i, (value, doc)) in variants.iter().enumerate() {
            if let Some(doc) = doc {
                out.push_str(&indent_doc(doc, 2));
            }
            let sep = if i + 1 == variants.len() { ";" } else { "" };
            out.push_str(&format!("  | \"{value}\"{sep}\n"));
        }
        return out;
    }

    // An internally-tagged union: `oneOf` of objects each with a `const` tag.
    if let Some(one_of) = def.get("oneOf").and_then(Value::as_array) {
        out.push_str(&format!("export type {name} =\n"));
        for (i, variant) in one_of.iter().enumerate() {
            let sep = if i + 1 == one_of.len() { ";" } else { "" };
            if let Some(doc) = doc_comment(variant, 2) {
                out.push_str(&doc);
            }
            out.push_str(&format!(
                "  | {}{sep}\n",
                inline_object(variant).unwrap_or_else(|| ts_type(variant))
            ));
        }
        return out;
    }

    // An untagged union: `anyOf` of plain types.
    if let Some(any_of) = def.get("anyOf").and_then(Value::as_array) {
        let parts: Vec<String> = any_of.iter().map(ts_type).collect();
        out.push_str(&format!("export type {name} = {};\n", parts.join(" | ")));
        return out;
    }

    if def.get("properties").is_some() {
        out.push_str(&format!("export interface {name} {{\n"));
        out.push_str(&render_properties(def, 2));
        out.push_str("}\n");
        return out;
    }

    out.push_str(&format!("export type {name} = {};\n", ts_type(def)));
    out
}

fn render_properties(def: &Value, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let mut out = String::new();

    let props = match def.get("properties").and_then(Value::as_object) {
        Some(p) => p,
        None => return out,
    };
    let required: Vec<&str> = def
        .get("required")
        .and_then(Value::as_array)
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    let mut names: Vec<&String> = props.keys().collect();
    names.sort();

    for name in names {
        let prop = &props[name];
        if let Some(doc) = doc_comment(prop, indent) {
            out.push_str(&doc);
        }
        // Fields serde fills from a default are optional here; the projection
        // itself always carries them, but a patch value need not.
        let opt = if required.contains(&name.as_str()) {
            ""
        } else {
            "?"
        };
        out.push_str(&format!("{pad}{name}{opt}: {};\n", ts_type(prop)));
    }
    out
}

/// Render a `oneOf` variant that is an object as an inline TS object type.
fn inline_object(variant: &Value) -> Option<String> {
    variant.get("properties")?;
    let body = render_properties(variant, 6);
    Some(format!("{{\n{body}    }}"))
}

fn string_enum_variants(def: &Value) -> Option<Vec<(String, Option<String>)>> {
    // Variants that carry doc comments: schemars gives each one its own
    // `const` subschema so it has somewhere to hang the `description`.
    if let Some(one_of) = def.get("oneOf").and_then(Value::as_array) {
        let mut out = Vec::new();
        for v in one_of {
            let c = v.get("const")?.as_str()?;
            out.push((
                c.to_string(),
                v.get("description")
                    .and_then(Value::as_str)
                    .map(str::to_string),
            ));
        }
        return Some(out);
    }

    // Variants with no doc comments: with nothing to describe, schemars
    // collapses the whole enum to a plain `enum` array. It is the same closed
    // set and has to render the same way — falling through to the catch-all
    // would emit `= string`, which costs the editor its dropdown and costs
    // every `switch` its exhaustiveness check, silently.
    if def.get("type").and_then(Value::as_str) != Some("string") {
        return None;
    }
    let values = def.get("enum")?.as_array()?;
    values
        .iter()
        .map(|v| Some((v.as_str()?.to_string(), None)))
        .collect()
}

fn ts_type(schema: &Value) -> String {
    if let Some(r) = schema.get("$ref").and_then(Value::as_str) {
        return r.rsplit('/').next().unwrap_or("unknown").to_string();
    }
    if let Some(c) = schema.get("const") {
        return match c {
            Value::String(s) => format!("\"{s}\""),
            other => other.to_string(),
        };
    }
    if let Some(any_of) = schema.get("anyOf").and_then(Value::as_array) {
        let parts: Vec<String> = any_of.iter().map(ts_type).collect();
        return parts.join(" | ");
    }
    if let Some(one_of) = schema.get("oneOf").and_then(Value::as_array) {
        let parts: Vec<String> = one_of
            .iter()
            .map(|v| inline_object(v).unwrap_or_else(|| ts_type(v)))
            .collect();
        return parts.join(" | ");
    }

    match schema.get("type") {
        Some(Value::String(t)) => scalar(t, schema),
        // `["integer", "null"]` and friends.
        Some(Value::Array(types)) => {
            let parts: Vec<String> = types
                .iter()
                .filter_map(Value::as_str)
                .map(|t| scalar(t, schema))
                .collect();
            parts.join(" | ")
        }
        _ => "unknown".to_string(),
    }
}

fn scalar(t: &str, schema: &Value) -> String {
    match t {
        "null" => "null".to_string(),
        "boolean" => "boolean".to_string(),
        "integer" | "number" => "number".to_string(),
        "string" => "string".to_string(),
        "array" => {
            let items = schema
                .get("items")
                .map(ts_type)
                .unwrap_or_else(|| "unknown".into());
            // Unions need parenthesising before `[]`.
            if items.contains('|') {
                format!("({items})[]")
            } else {
                format!("{items}[]")
            }
        }
        "object" => match schema.get("additionalProperties") {
            Some(Value::Bool(false)) | None => {
                if schema.get("properties").is_some() {
                    let body = render_properties(schema, 2);
                    format!("{{\n{body}}}")
                } else {
                    "Record<string, unknown>".to_string()
                }
            }
            Some(v) => format!("Record<string, {}>", ts_type(v)),
        },
        _ => "unknown".to_string(),
    }
}

/// A `description` rendered as a JSDoc block at the given indent.
fn doc_comment(schema: &Value, indent: usize) -> Option<String> {
    let text = schema.get("description")?.as_str()?;
    Some(indent_doc(text, indent))
}

fn indent_doc(text: &str, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let mut out = format!("{pad}/**\n");
    for line in text.lines() {
        if line.is_empty() {
            out.push_str(&format!("{pad} *\n"));
        } else {
            out.push_str(&format!("{pad} * {line}\n"));
        }
    }
    out.push_str(&format!("{pad} */\n"));
    out
}

/// Convenience: render the config schema, which is what `rpc-codegen` emits.
pub fn render_config_types() -> String {
    let schema = crate::config_schema::config_schema();
    let value: Value = serde_json::to_value(&schema).expect("schema serializes");
    render(&value, "RawConfig")
}

#[allow(dead_code)]
fn unused(_: &Map<String, Value>) {}
