#!/usr/bin/env bash
# Out-of-band interactive dev harness for the wlroots swipe keyboard.
#
# Opens a nested Sway compositor (a window on your desktop) running the swipe keyboard docked at
# the bottom plus a text field above it, so you can swipe-type with the mouse (the pointer
# fallback stands in for touch) or a touchscreen and watch words commit — with no gdm and no
# shepherd-launcher involved.
#
# The keyboard commits via input-method-v2, so the text target must be a GTK/text-input-v3 app
# (gnome-text-editor, zenity); a terminal (foot) only shows that the keyboard renders — it does
# not receive IM commits.
#
# Usage:
#   scripts/dev-keyboard-wlroots.sh [--profile adult|child] [--app gnome-text-editor|zenity|foot]
# Inside the nested window: swipe/tap to type; press Alt+q (or close the window) to quit.
#
# CI/wiring check (no window, just confirm everything comes up): SWAY_HEADLESS=1 ... (the harness
# then runs Sway headless and exits after a short bring-up; combine with a timeout).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

PROFILE="adult"
APP=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --profile) PROFILE="${2:?}"; shift 2 ;;
        --app) APP="${2:?}"; shift 2 ;;
        *) die "unknown argument: $1" ;;
    esac
done

command -v sway >/dev/null 2>&1 || die "sway is required"

KBD_BIN=""
for cand in "$REPO_ROOT/target/release/shepherd-keyboard-wlroots" \
            "$REPO_ROOT/target/debug/shepherd-keyboard-wlroots"; do
    [[ -x "$cand" ]] && { KBD_BIN="$cand"; break; }
done
[[ -n "$KBD_BIN" ]] || die "keyboard not built: cargo build -p shepherd-keyboard-wlroots"

BUNDLE_DIR="${SHEPHERD_SWIPE_BUNDLE_DIR:-$REPO_ROOT/dev-runtime/swipe-bundles}"
[[ -d "$BUNDLE_DIR/$PROFILE" ]] \
    || warn "no $PROFILE bundle at $BUNDLE_DIR/$PROFILE — the keyboard will fail closed to tap-only (run scripts/fetch-swipe-bundles.sh)"

# Pick a text target. GTK apps receive input-method-v2 commits; terminals do not.
if [[ -z "$APP" ]]; then
    for cand in gnome-text-editor zenity foot; do
        command -v "$cand" >/dev/null 2>&1 && { APP="$cand"; break; }
    done
fi
[[ -n "$APP" ]] || die "no text app found (install gnome-text-editor or zenity)"
case "$APP" in
    gnome-text-editor) APP_CMD="gnome-text-editor" ;;
    zenity) APP_CMD="zenity --entry --title=swipe-test --text='Swipe-type here:'" ;;
    foot) APP_CMD="foot"; warn "foot is a terminal — it shows the keyboard but won't receive IM commits; use gnome-text-editor/zenity to see committed text" ;;
    *) APP_CMD="$APP" ;;
esac

CONF="$(mktemp --suffix=.sway-keyboard-dev)"
trap 'rm -f "$CONF"' EXIT
cat >"$CONF" <<EOF
# Nested Sway for swipe-keyboard development (generated by dev-keyboard-wlroots.sh).
output * resolution 1100x850
exec env SHEPHERD_SWIPE_BUNDLE_DIR="$BUNDLE_DIR" RUST_LOG=info "$KBD_BIN" --profile "$PROFILE"
exec $APP_CMD
bindsym Mod1+q exit
EOF

# Software rendering keeps it reliable in VMs/headless.
export WLR_RENDERER="${WLR_RENDERER:-pixman}"
export LIBGL_ALWAYS_SOFTWARE="${LIBGL_ALWAYS_SOFTWARE:-1}"

if [[ "${SWAY_HEADLESS:-0}" == "1" ]]; then
    info "Bring-up check: nested Sway (headless) + keyboard ($PROFILE) + $APP"
    export WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1
else
    info "Launching nested Sway window: swipe keyboard ($PROFILE) + $APP"
    info "Swipe/tap to type; commits land in the text app. Quit with Alt+q or by closing the window."
    export WLR_BACKENDS="${WLR_BACKENDS:-wayland}"
fi

exec sway -c "$CONF"
