//! BLE glue over `shepherd_management::dispatch_json`.
//!
//! Claim-flow methods (`claim`, `factory_reset`) are *not* handled here
//! — they live on [`crate::claim::ClaimMachine`] and the server routes
//! them before falling through to this dispatcher.
//!
//! Everything else — method-name matching, param parsing, result
//! wrapping — is generated by the `#[management_rpc]` attribute on the
//! `ManagementService` trait. This module is now just a ~30-line
//! adapter that turns an [`RpcRequest`] into an [`RpcResponse`] by
//! calling into the auto-generated dispatcher and mapping its
//! `RpcDispatchError` variants onto BLE's [`ErrorCode`].

use shepherd_management::{ManagementService, RpcDispatchError, dispatch_json};

use crate::protocol::{ErrorCode, RpcRequest, RpcResponse};

/// Dispatch one `ManagementService` method by name. Returns an
/// `RpcResponse` ready to be framed and pushed onto the outbox.
pub async fn dispatch_management(svc: &dyn ManagementService, request: RpcRequest) -> RpcResponse {
    let id = request.id;
    match dispatch_json(svc, &request.method, request.params).await {
        Ok(value) => RpcResponse::ok(id, value),
        Err(RpcDispatchError::MethodNotFound(msg)) => RpcResponse::err(
            id,
            ErrorCode::MethodNotFound,
            format!("unknown method '{msg}'"),
        ),
        Err(RpcDispatchError::InvalidParams(msg)) => {
            RpcResponse::err(id, ErrorCode::InvalidParams, msg)
        }
        Err(RpcDispatchError::Serialization(msg)) => RpcResponse::err(id, ErrorCode::Internal, msg),
        Err(RpcDispatchError::Management(e)) => RpcResponse::from_management_err(id, e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testsupport::{MockSvc, req};

    #[tokio::test]
    async fn health_dispatches_to_service() {
        let svc = MockSvc::new();
        let resp = dispatch_management(&svc, req(1, "health", serde_json::Value::Null)).await;
        assert_eq!(resp.id, 1);
        assert!(resp.error.is_none());
        assert_eq!(*svc.health_calls.lock().await, 1);
    }

    #[tokio::test]
    async fn unknown_method_returns_method_not_found() {
        let svc = MockSvc::new();
        let resp =
            dispatch_management(&svc, req(9, "no_such_method", serde_json::Value::Null)).await;
        assert_eq!(resp.id, 9);
        let err = resp.error.unwrap();
        assert_eq!(err.code, ErrorCode::MethodNotFound);
    }

    #[tokio::test]
    async fn invalid_params_returns_invalid_params() {
        let svc = MockSvc::new();
        // get_entry needs an `id`, so {} is invalid.
        let resp = dispatch_management(&svc, req(3, "get_entry", serde_json::json!({}))).await;
        assert_eq!(resp.error.unwrap().code, ErrorCode::InvalidParams);
    }

    #[tokio::test]
    async fn management_error_maps_to_rpc_error() {
        let svc = MockSvc::new();
        let resp = dispatch_management(
            &svc,
            req(4, "get_entry", serde_json::json!({"id": "missing"})),
        )
        .await;
        assert_eq!(resp.error.unwrap().code, ErrorCode::NotFound);
    }

    #[tokio::test]
    async fn logout_returns_null_result() {
        let svc = MockSvc::new();
        let resp = dispatch_management(&svc, req(5, "logout", serde_json::Value::Null)).await;
        assert!(resp.error.is_none());
        assert_eq!(resp.result, Some(serde_json::Value::Null));
    }

    #[tokio::test]
    async fn delete_override_wraps_bool_result() {
        // Regression check that `#[rpc(wrap_result = "deleted")]` on
        // the trait actually produces `{"deleted": <bool>}` on the
        // wire — clients (both the web-ui and the companion) parse
        // this field explicitly.
        let svc = MockSvc::new();
        let resp = dispatch_management(
            &svc,
            req(6, "delete_override", serde_json::json!({"id": "steam-goo"})),
        )
        .await;
        assert!(resp.error.is_none());
        let result = resp.result.unwrap();
        assert!(result.get("deleted").is_some());
    }

    #[tokio::test]
    async fn zero_arg_method_accepts_object_or_null_params() {
        let svc = MockSvc::new();
        // Zero-arg methods should accept both `{}` and `Value::Null`
        // as a params blob. `health` returns a real value in the mock
        // (unlike `service_state`, which is `unreachable!`).
        let a = dispatch_management(&svc, req(7, "health", serde_json::json!({}))).await;
        let b = dispatch_management(&svc, req(8, "health", serde_json::Value::Null)).await;
        assert!(a.error.is_none());
        assert!(b.error.is_none());
    }
}
